### PR TITLE
fix: show 0 instead of NaN on gov page when nobody has voted

### LINKED ISSUE #310: When nobody has voted, Governance page shows `NaN`
image

### PR DESCRIPTION
**Pull request by imcoolbean**
Fixes #310

### CODE REVIEW

File: projects/ui/src/components/Governance/Actions/Vote.tsx [hunk 1]
```diff
@@ -77,7 +77,7 @@ const VoteForm: FC<FormikProps<VoteFormValues> & {
   //     <CircularProgress variant="determinate" value={(quorumPctComplete.times(100)).toNumber()} size={12} thickness={8}  />
   //   </>
   // )}
-
+  console.log('VOTEEE', displayFullBN(new BigNumber(null || 0)))
```
Comment (hellofromguy) [inline projects/ui/src/components/Governance/Actions/Vote.tsx:80]: remove?

Comment (colestriler) [reply projects/ui/src/components/Governance/Actions/Vote.tsx]: Fixed

Comment (imcoolbean) [reply projects/ui/src/components/Governance/Actions/Vote.tsx]: Fixed

**Review by silochad — APPROVED** [review]
